# TODO
# If I comment, tf validate, it should run
# tf fmt
# tf validate
# tfsec, tfline

# I want plan or apply stages to run only if validate stage is successful


name: Run Terraform Plan or Apply via PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump full event payload (for debugging)
        run: echo '${{ toJson(github.event) }}'

  terraform-plan:
    if: |
      github.event.issue.pull_request && github.event.comment.body == 'terraform plan'
    runs-on: ubuntu-latest
    needs: dump-event
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Comment back on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "✅ Terraform plan completed successfully." || echo "Could not post comment"

terraform-apply:
  if: |
    github.event.issue.pull_request &&
    github.event.comment.body == 'terraform apply'
  runs-on: ubuntu-latest
  needs: dump-event
  steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Check if PR is approved
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_NUMBER=${{ github.event.issue.number }}
        # Get the latest review state that is 'APPROVED' for this PR
        APPROVED=$(gh pr reviews $PR_NUMBER --json state --jq '.[] | select(.state == "APPROVED") | .state' || echo "")
        if [[ -z "$APPROVED" ]]; then
          echo "❌ PR #$PR_NUMBER is NOT approved. Cannot run terraform apply."
          exit 1
        else
          echo "✅ PR #$PR_NUMBER is approved. Proceeding with terraform apply."
        fi

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.6.6

    - name: Terraform Init
      run: terraform init

    - name: Terraform Apply
      run: terraform apply -auto-approve

    - name: Comment back on PR
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        gh pr comment ${{ github.event.issue.number }} --body "✅ Terraform apply completed successfully." || echo "Could not post comment"
