name: Run Terraform Plan via PR Comment

on:
  issue_comment:
    types: [created]

jobs:
  dump-event:
    runs-on: ubuntu-latest
    steps:
      - name: Dump full event payload (for debugging)
        run: echo '${{ toJson(github.event) }}'

  terraform-plan:
    if: |
      github.event.issue.pull_request &&
      github.event.comment.body == 'terraform plan'
    runs-on: ubuntu-latest
    needs: dump-event

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.6.6  # Change as needed

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Comment back on PR
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh pr comment ${{ github.event.issue.number }} --body "✅ Terraform plan completed successfully." || echo "Could not post comment"
