name: GitHub Actions Events Demo
run-name: GitHub Actions Events
on:
  repository_dispatch:
    types: [test_result]
jobs:
  Get-Environment-Variables:
    runs-on: ubuntu-latest
    steps:
    - name: Read environment variables
      run: |
        echo "GITHUB_EVENT_NAME: ${{ github.event_name }}"
        echo "GITHUB_SHA: ${{ github.sha }}"
        echo "GITHUB_REF: ${{ github.ref }}"
        echo "GITHUB_REF_NAME: ${{ github.ref_name }}"
    - name: Parsing client payload message
      run: |
        echo $MESSAGE
      env:
        MESSAGE: ${{ github.event.client_payload.message }}



# {"event_type":"test_result","client_payload":{"unit":false,"integration":true, "message":"testing github actions"}}